#!/usr/bin/env python

from nd import *
import sys

def usage():
   print "Usage: %s -f <filename> -s <subject>" % sys.argv[0]
   sys.exit(1)

if len(sys.argv) != 5: usage()
prog, f, filename, s, subject = sys.argv
if f != "-f" or s != "-s": usage()
if not subject: usage()


if User.myself() not in Privilege("memberinfo").member:
   print "you're not in the memberinfo group, so this script isn't going to work"
   sys.exit(1)

# for each current member
for u in User.search(tcdnetsoc_membership_year=current_session()):
   u.sendmail(filename, From='Netsoc PRO <pro@netsoc.tcd.ie>', Subject="[Netsoc] %s" % subject)
